<a href="https://colab.research.google.com/github/1801019/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# sklearnでエラーが出るので、前のバージョンを入れ直す¶

In [3]:
# 現在のscikitーlearnをcolabのVMからアンインストール
!pip uninstall scikit-learn
# 前のバージョンを指定してvmにいんすとーる
!pip install scikit-learn==0.20 --ignore-installed

Uninstalling scikit-learn-0.22.2.post1:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/scikit_learn-0.22.2.post1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-0.22.2.post1
     |████████████████████████████████| 5.3MB 3.3MB/s 
     |████████████████████████████████| 25.9MB 1.7MB/s 
     |████████████████████████████████| 14.9MB 313kB/s 
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.3 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement scipy==1.4.1, but you'll have scipy 1.5.3 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.


 ### all_estimators()でループして各種のアルゴリズムで学習させ、比較する

In [4]:
# ライブラリ読み込み
import pandas as pd
# 学習用データとテスト検証用データを分割する
from sklearn.model_selection import train_test_split
# 正解率を算出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimaios(推定機の全てを利用できるようにする)
from sklearn.utils.testing import all_estimators
# 警告クラス
import warnings


### Webからあやめのデータを読み込む

In [26]:
# urリンクから読み込むライブラリ
import urllib.request as req
# url用の文字列変数を定義
url ="https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
#リンクから保存するためのファイル名を定義
savefile = "iris.csv"
# requestクラスを使ってurlからデータをsavefileへコピーして保存
req.urlretrieve(url,savefile)
#pandasのreadメソッドを使ってcsvファイルを読み込む
iris_data = pd.read_csv(savefile,encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [27]:
y = iris_data.loc[:, "Name"] #目的変数
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]] #説明変数

print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


###アヤメデータを目的変数yと説明変数xに分離する

In [28]:
# 学習用データ（train）と検証用データ（test）に分離
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,train_size=0.8,shuffle=True)
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())


     SepalLength  SepalWidth  PetalLength  PetalWidth
13           4.3         3.0          1.1         0.1
92           5.8         2.6          4.0         1.2
24           4.8         3.4          1.9         0.2
106          4.9         2.5          4.5         1.7
115          6.4         3.2          5.3         2.3
13         Iris-setosa
92     Iris-versicolor
24         Iris-setosa
106     Iris-virginica
115     Iris-virginica
Name: Name, dtype: object
     SepalLength  SepalWidth  PetalLength  PetalWidth
42           4.4         3.2          1.3         0.2
10           5.4         3.7          1.5         0.2
30           4.8         3.1          1.6         0.2
1            4.9         3.0          1.4         0.2
101          5.8         2.7          5.1         1.9
42        Iris-setosa
10        Iris-setosa
30        Iris-setosa
1         Iris-setosa
101    Iris-virginica
Name: Name, dtype: object


In [29]:

# 推定器のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
# ワーニングを無視する
warnings.filterwarnings("ignore")

In [30]:
#推定器のリストをループ
for(name,algorithm) in allAlgorithms:
  #各アルゴリズムのオブジェクトを生成
  clf = algorithm() # 各アルゴリズムクラスのコンストラクトを実行
  #　学習させる
  clf.fit(x_train,y_train)
  # 推論する
  y_pred = clf.predict(x_test)
  # accuracy_scoreで正解率を算出して表示
  print(name,"正解率 = ",accuracy_score(y_test,y_pred) )

AdaBoostClassifier 正解率 =  1.0
BaggingClassifier 正解率 =  1.0
BernoulliNB 正解率 =  0.16666666666666666
CalibratedClassifierCV 正解率 =  0.9666666666666667
ComplementNB 正解率 =  0.8333333333333334
DecisionTreeClassifier 正解率 =  1.0
ExtraTreeClassifier 正解率 =  0.9333333333333333
ExtraTreesClassifier 正解率 =  1.0
GaussianNB 正解率 =  1.0
GaussianProcessClassifier 正解率 =  1.0
GradientBoostingClassifier 正解率 =  1.0
KNeighborsClassifier 正解率 =  1.0
LabelPropagation 正解率 =  1.0
LabelSpreading 正解率 =  1.0
LinearDiscriminantAnalysis 正解率 =  1.0
LinearSVC 正解率 =  1.0
LogisticRegression 正解率 =  0.9666666666666667
LogisticRegressionCV 正解率 =  0.9666666666666667
MLPClassifier 正解率 =  1.0
MultinomialNB 正解率 =  0.6
NearestCentroid 正解率 =  0.9666666666666667
NuSVC 正解率 =  0.9666666666666667
PassiveAggressiveClassifier 正解率 =  0.8333333333333334
Perceptron 正解率 =  0.16666666666666666
QuadraticDiscriminantAnalysis 正解率 =  1.0
RadiusNeighborsClassifier 正解率 =  0.9333333333333333
RandomForestClassifier 正解率 =  1.0
RidgeClassifier 正解率 =  0.

### クロスバリデーション関連のライブラリのインポート


In [31]:
#推定器のリストをループ
for(name,algorithm) in allAlgorithms:
  #各アルゴリズムのオブジェクトを生成
  clf = algorithm() # 各アルゴリズムクラスのコンストラクトを実行
  #　学習させる
  clf.fit(x_train,y_train)
  # 推論する
  y_pred = clf.predict(x_test)
  # accuracy_scoreで正解率を算出して表示
  print(name,"正解率 = ",accuracy_score(y_test,y_pred) )

AdaBoostClassifier 正解率 =  1.0
BaggingClassifier 正解率 =  1.0
BernoulliNB 正解率 =  0.16666666666666666
CalibratedClassifierCV 正解率 =  0.9666666666666667
ComplementNB 正解率 =  0.8333333333333334
DecisionTreeClassifier 正解率 =  1.0
ExtraTreeClassifier 正解率 =  1.0
ExtraTreesClassifier 正解率 =  1.0
GaussianNB 正解率 =  1.0
GaussianProcessClassifier 正解率 =  1.0
GradientBoostingClassifier 正解率 =  1.0
KNeighborsClassifier 正解率 =  1.0
LabelPropagation 正解率 =  1.0
LabelSpreading 正解率 =  1.0
LinearDiscriminantAnalysis 正解率 =  1.0
LinearSVC 正解率 =  1.0
LogisticRegression 正解率 =  0.9666666666666667
LogisticRegressionCV 正解率 =  0.9666666666666667
MLPClassifier 正解率 =  1.0
MultinomialNB 正解率 =  0.6
NearestCentroid 正解率 =  0.9666666666666667
NuSVC 正解率 =  0.9666666666666667
PassiveAggressiveClassifier 正解率 =  0.9666666666666667
Perceptron 正解率 =  0.16666666666666666
QuadraticDiscriminantAnalysis 正解率 =  1.0
RadiusNeighborsClassifier 正解率 =  0.9333333333333333
RandomForestClassifier 正解率 =  1.0
RidgeClassifier 正解率 =  0.933333333333333

### クロスバリデーションを一致させる

In [32]:
# ライブラリのインポート
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [33]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True)
# 　すでに生成してあるall_astimatorsのインスタンスをループさせて、クロスバリデーション を行う
for(name,algorithm) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    #scoreの属性がある学習モデルだけに送る
    if hasattr(clf,"score"):
      scores = cross_val_score(clf,x,y,cv=kfold_cv)
      #k=n splits=5回分のクロスバリデーション のスコアを表示
      print(name,"の正解率")
      print(scores)
      #ifブロック終了
    #tryブロック終了
  except : #例外処理のブロック
    #何もしない
    pass

AdaBoostClassifier の正解率
[0.9        1.         0.96666667 0.93333333 0.96666667]
BaggingClassifier の正解率
[0.96666667 0.96666667 1.         0.9        0.9       ]
BernoulliNB の正解率
[0.23333333 0.26666667 0.3        0.26666667 0.23333333]
CalibratedClassifierCV の正解率
[0.96666667 0.93333333 0.9        0.96666667 0.86666667]
ComplementNB の正解率
[0.86666667 0.5        0.8        0.56666667 0.6       ]
DecisionTreeClassifier の正解率
[0.93333333 0.96666667 0.93333333 0.93333333 0.96666667]
ExtraTreeClassifier の正解率
[0.83333333 1.         0.9        0.93333333 1.        ]
ExtraTreesClassifier の正解率
[0.93333333 1.         0.93333333 0.96666667 0.86666667]
GaussianNB の正解率
[0.96666667 1.         0.96666667 0.93333333 0.9       ]
GaussianProcessClassifier の正解率
[0.93333333 0.96666667 0.93333333 1.         0.96666667]
GradientBoostingClassifier の正解率
[0.96666667 0.93333333 1.         0.96666667 0.93333333]
KNeighborsClassifier の正解率
[0.96666667 0.96666667 0.96666667 0.96666667 1.        ]
LabelPropagation の正解率


In [34]:
#ライブラリのインポート
from sklearn.model_selection import cross_validate

In [35]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True)
# 　すでに生成してあるall_astimatorsのインスタンスをループさせて、クロスバリデーション を行う
for(name,algorithm) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    #scoreの属性がある学習モデルだけに送る
    if hasattr(clf,"score"):
      scores = cross_validate(clf,x,y,cv=kfold_cv)
      #k=n splits=5回分のクロスバリデーション のスコアを表示
      print(name,"の正解率")
      print(scores)
      #ifブロック終了
    #tryブロック終了
  except : #例外処理のブロック
    #何もしない
    pass


AdaBoostClassifier の正解率
{'fit_time': array([0.06875467, 0.06362057, 0.06053257, 0.06220388, 0.06528807]), 'score_time': array([0.00545692, 0.00565124, 0.00555253, 0.0062983 , 0.00591302]), 'test_score': array([0.9       , 0.93333333, 0.9       , 1.        , 0.9       ]), 'train_score': array([0.98333333, 0.96666667, 0.95833333, 0.95      , 0.95833333])}
BaggingClassifier の正解率
{'fit_time': array([0.01702285, 0.01297736, 0.01444006, 0.01321387, 0.01303411]), 'score_time': array([0.00177765, 0.00199151, 0.00186253, 0.00179124, 0.00179219]), 'test_score': array([0.96666667, 0.96666667, 0.93333333, 0.9       , 0.93333333]), 'train_score': array([1.        , 0.99166667, 0.98333333, 1.        , 1.        ])}
BernoulliNB の正解率
{'fit_time': array([0.00288177, 0.00290275, 0.00350475, 0.00181675, 0.00180769]), 'score_time': array([0.00138497, 0.00156617, 0.00089312, 0.00081635, 0.00081801]), 'test_score': array([0.26666667, 0.26666667, 0.2       , 0.23333333, 0.26666667]), 'train_score': array([0.

### ライブラリをインポート

In [36]:
#グリッドサーチのオブジェクトクラスをインポート
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [37]:
#グリッドサーチで試すパラメータのパターンを指定する
parameters = [
              #３つのパラメータ、3パターン
              {"C":[1,10,100,1000],"kernel":["linear"]},
              {"C":[1,10,100,1000],"kernel":["rbf"],"gamma":[0.001,0.0001]},
              {"C":[1,10,100,1000],"kernel":["sigmoid"],"gamma":[0.001,0.0001]}
              ]
#普通の学習
clf = SVC()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print ("普通の学習の正解率＝",accuracy_score(y_test, y_pred))

#グリッドサーチを行う
#K分割交差検証のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True)
#グリッドサーチの中でK分割交差検証も行われる
clf_grid = GridSearchCV( SVC(), parameters, cv=kfold_cv )#インスタンス
clf_grid.fit(x_train, y_train)#学習
#学習済みのもでs流に最終的に設定されたパラメータを表示
print("最適なパラメータ＝", clf_grid.best_estimator_ )

#最適なパラメータ設定済みの学習モデルで評価
y_pred = clf_grid.predict(x_test)
print("グリッドサーチの正解率＝", accuracy_score(y_test,y_pred))

普通の学習の正解率＝ 1.0
最適なパラメータ＝ SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
グリッドサーチの正解率＝ 1.0


### Numpyの動作確認

In [38]:
#import
import numpy as np

In [39]:
#numpy配列の初期化
a = np.array([1,2,3,4,5])
print(a)
#type関数で型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [40]:
#2次元配列のnbarryを定義
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [41]:
#配列の要素数を指定する
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [42]:
#連番の要素数を指定して初期化
print(np.arange(5))#0から5未満
print(np.arange(2,9))#２から８未満
print(np.arange(5,8,0.5))#５から８未満で0.5刻み

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [43]:
a = np.array([1,2,3,4,5])
b = a*2
print(b)
x = np.arange(10)
print(x)
y = 3*x + 5
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [44]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [45]:
# Numpy配列で次元数を変換する
a = np.array([[1,2,3],[4,5,6]])
print("a=", a)
b = a.flatten()
print("b=", b)

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape(3,2)
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [47]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]
print(a) # 二次元配列の０行目
b = v[1:] #  一列目いこう
print(b)
c = v[:,0]
print(c)

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
